config/routes.rb
Rails.application.routes.draw do
  resources :offerings
  root 'offerings#index'

  resources :courses
  devise_for :users

resources :offerings do
  resources :courses

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all

    elsif user.student?
      can :read, Offering
      can :read, Course
    else
      can :read , Offering
      can :read, Course
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
has_and_belongs_to_many :offering
end

app/models/offering.rb
class Offering < ApplicationRecord
has_and_belongs_to_many :courses
end

app/models/role.rb
class Role < ApplicationRecord
has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  before_validation :assign_role

  def assign_role
    self.role = "Student" if self.role.nil?
  end
  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end
  def student?
    self.role.name == "Student" if !self.role.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_offering, only: [:create]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  # GET /courses
  # GET /courses.json

  def set_offering
    @offering=Offering.find(params[:offering_id])
  end

  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create

    #@course.user = current_user

    respond_to do |format|
      if @offering.courses.create(course_params)
        format.html { redirect_to @offering, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @offering }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    #@course.user = current_user
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:code, :title)
    end
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  before_action :set_offering, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  # GET /offerings
  # GET /offerings.json
  def index
    @offerings = Offering.all
  end

  # GET /offerings/1
  # GET /offerings/1.json
  def show
  end

  # GET /offerings/new
  def new
    @offering = Offering.new
  end

  # GET /offerings/1/edit
  def edit
  end

  # POST /offerings
  # POST /offerings.json
  def create
    @offering = Offering.new(offering_params)

    respond_to do |format|
      if @offering.save
        format.html { redirect_to @offering, notice: 'Offering was successfully created.' }
        format.json { render :show, status: :created, location: @offering }
      else
        format.html { render :new }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerings/1
  # PATCH/PUT /offerings/1.json
  def update
    respond_to do |format|
      if @offering.update(offering_params)
        format.html { redirect_to @offering, notice: 'Offering was successfully updated.' }
        format.json { render :show, status: :ok, location: @offering }
      else
        format.html { render :edit }
        format.json { render json: @offering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerings/1
  # DELETE /offerings/1.json
  def destroy
    @offering.destroy
    respond_to do |format|
      format.html { redirect_to offerings_url, notice: 'Offering was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offering
      @offering = Offering.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offering_params
      params.require(:offering).permit(:year, :semester)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final2017v3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:error] %>
    <div id="error">
      <p><%= flash[:error] %></p>
    </div>
  <% elsif flash[:alert] %>
    <div>
      <p><%= flash[:alert] %></p>
    </div>
  <% end %>
  <div id="container">
    <% if user_signed_in? %>
      Welcome
      <%= current_user.email %>! Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      or
      <%= link_to "Sign in", new_user_session_path %>.
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/offerings/_form.html.erb
<%= form_with(model: offering, local: true) do |form| %>
  <% if offering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offering.errors.count, "error") %> prohibited this offering from being saved:</h2>

      <ul>
      <% offering.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offerings/edit.html.erb
<h1>Editing Offering</h1>

<%= render 'form', offering: @offering %>

<%= link_to 'Show', @offering %> |
<%= link_to 'Back', offerings_path %>

app/views/offerings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offerings</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.year %></td>
        <td><%= offering.semester %></td>
        <td><%= link_to 'Show', offering %></td>
        <td><%= link_to 'Edit', edit_offering_path(offering) %></td>
        <td><%= link_to 'Destroy', offering, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offering', new_offering_path %>

app/views/offerings/new.html.erb
<h1>New Offering</h1>

<%= render 'form', offering: @offering %>

<%= link_to 'Back', offerings_path %>

app/views/offerings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @offering.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @offering.semester %>
</p>


<h2>Courses offered</h2>
<table>
  <thead>
  <tr>
    <th>Code</th>
    <th>Title</th>
    <th>Register this course</th>
  </tr>
  </thead>
  <tbody>
  <% @offering.courses.each do |course| %>
    <tr>
      <td><%= course.code %></td>
      <td><%= course.title %></td>
      <td><%= link_to 'Register', offerings_path %></td>

    </tr>
  <% end %>
  </tbody>
</table>
<br/>
<h2>Add a course:</h2>
<%= form_for([@offering, @offering.courses.build]) do |f| %>
  <div class="field">
    <%= f.label :code %>
    <br/>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_offering_path(@offering) %> |
<%= link_to 'Back', offerings_path %>